.gitignore
.prettierignore
.travis.yml
README.md
app/getContainer.ts
app/modules/web3/BrowserWallet.ts
app/modules/web3/LedgerWallet.ts
app/modules/web3/PersonalWeb3.ts
app/modules/web3/Web3Adapter.ts
app/modules/web3/Web3Manager.ts
app/modules/web3/actions.ts
app/modules/web3/reducer.ts
app/store.ts
app/types.d.ts
package.json
test/components/walletSelector/WalletSelector.spec.tsx
test/fixtures.ts
test/modules/wallet-selector/browser-wallet/actions.spec.ts
test/modules/wallet-selector/ledger-wizard/actions.spec.ts
test/modules/web3/Web3Adapter.spec.ts
test/modules/web3/Web3Manager.spec.ts
test/modules/web3/reducer.spec.ts
test/types.d.ts
tsconfig.dev.json
webpack/webpack.config.dev.js

- recognize web3 node type 
- put information about currently connected wallet to redux
- opaque type for networkId - additional type safety
dev:
- transpile to es2017 in dev mode
- add new task `yarn test:fix` (like `lint:fix` but runs tests as well)

Web3 redux state

---

app/components/App.tsx
app/components/AppRouter.tsx
app/components/Dashboard.tsx
app/components/Header.tsx
app/components/Home.tsx
app/components/Success.tsx
app/components/walletSelector/WalletRouter.tsx
app/components/walletSelector/WalletSelector.tsx
app/modules/wallet-selector/actions.ts
app/modules/wallet-selector/browser-wizard/actions.ts
app/modules/wallet-selector/ledger-wizard/actions.ts
app/store.ts
test/components/Header.spec.tsx
test/components/Home.spec.tsx
test/components/walletSelector/WalletSelector.spec.tsx
test/modules/wallet-selector/actions.spec.ts
test/modules/wallet-selector/browser-wallet/actions.spec.ts
test/modules/wallet-selector/ledger-wizard/actions.spec.ts

tweak app routes, show authorized header after signin

---

app/components/walletSelector/WalletLedgerChooser.tsx
app/components/walletSelector/WalletLedgerChooserComponent.tsx
app/components/walletSelector/WalletLedgerDPChooser.tsx
app/modules/wallet-selector/ledger-wizard/actions.ts
app/modules/wallet-selector/ledger-wizard/reducer.ts
app/store.ts
test/components/walletSelector/WalletLedgerChooserComponent.spec.tsx
test/modules/wallet-selector/ledger-wizard/actions.spec.ts
test/modules/wallet-selector/ledger-wizard/reducer.spec.ts

This is new feature for existing PR #44. To ease checking I created separate PR that would be merged into `derivation_path_fix` branch

On derivation path prefix error hide accounts

---

app/modules/wallet-selector/ledger-wizard/actions.ts
app/modules/wallet-selector/ledger-wizard/reducer.ts
test/modules/wallet-selector/ledger-wizard/actions.spec.ts
test/modules/wallet-selector/ledger-wizard/reducer.spec.ts

This is new feature for existing PR #44. To ease checking I created separate PR that would be merged into `derivation_path_fix` branch

Prevent race condition on derivation path selector

---

app/components/App.tsx
app/getContainer.ts
app/lib/index.ts
app/modules/kyc/sagas.ts
app/modules/networking/JsonHttpClient.ts
app/modules/networking/SignatureAuthApi.ts
app/modules/networking/UsersApi.ts
app/modules/networking/VaultApi.ts
app/modules/networking/jwt-actions.ts
app/modules/notifications/NotificationCenter.ts
app/modules/notifications/notifyOnErrorAction.ts
app/modules/routing/sagas.ts
app/modules/sagas.ts
app/modules/storage/storage.ts
app/modules/userAgent/actions.ts
app/modules/wallet-selector/actions.ts
app/modules/wallet-selector/browser-wizard/actions.ts
app/modules/wallet-selector/ledger-wizard/actions.ts
app/modules/wallet-selector/light-wizard/actions.ts
app/modules/web3/BrowserWallet.ts
app/modules/web3/LedgerWallet.ts
app/modules/web3/LightWallet.ts
app/modules/web3/Web3Manager.ts
app/modules/web3/actions.ts
app/redux-injectify.ts
app/utils/AsyncIntervalScheduler.ts
app/utils/Logger.ts
app/utils/cryptoRandomString.ts
test/components/walletSelector/WalletSelector.spec.tsx
test/integrationTestUtils.tsx

All DI symbols use es6 `symbol`.
All DI symbols are uppercased with `_SYMBOL` at the end

refactor all DI symbols

---

app/lib/api/VaultApi.ts

Adds get method to VaultAPI

---

app/components/AppRouter.tsx
app/components/WalletLoginHelp.tsx
app/components/walletSelector/walletLight/WalletResetHeader.tsx
app/styles/variables.scss

Adds Password Reset Component

---

app/components/walletSelector/walletLight/WalletResetHeader.tsx
app/components/walletSelector/walletLight/resetPasswordSuccsess.tsx

Adds Reset your password done page

---

app/components/shared/ProgressStepper.module.scss
app/components/shared/ProgressStepper.tsx
app/styles/variables.scss

Restyle progress bar

---

app/components/App.tsx
app/components/walletSelector/WalletSelector.module.scss
app/components/walletSelector/WalletSelector.tsx
app/styles/variables.scss

Restyle of wallet chooser and replace unnecessary div with <>

---

app/lib/web3/LightWallet.ts
package.json
typings/modules.d.ts
yarn.lock

This implements rudolfix's solution for Sign Message

Fixes lightWallet sign Message

---

app/components/shared/Navigation.module.scss
app/components/shared/Navigation.tsx
app/components/walletSelector/WalletLedgerChooserTableAdvanced.module.scss
app/components/walletSelector/WalletLedgerChooserTableAdvanced.spec.tsx
app/components/walletSelector/WalletLedgerChooserTableAdvanced.tsx
app/styles/variables.scss

Add Navigation components

---

app/components/Demo.tsx
app/components/walletSelector/WalletLedgerDPChooser.spec.tsx
app/components/walletSelector/WalletLedgerDPChooser.tsx
app/styles/variables.scss

advanced ledger addres chooser input restyle

---

app/components/shared/forms/formField/FormField.tsx
app/components/walletSelector/walletRegister/RegisterWallet.tsx

Use reactstrap FormFeedback in FormField component

---

app/components/AppRouter.tsx
app/components/Home.tsx
app/components/walletSelector/WalletLedgerChooserComponent.tsx
app/components/walletSelector/WalletLedgerInitComponent.tsx
app/components/walletSelector/WalletMessageSigner.tsx
app/components/walletSelector/WalletRouter.tsx
app/components/walletSelector/WalletSelector.module.scss
app/components/walletSelector/WalletSelector.spec.tsx
app/components/walletSelector/WalletSelector.tsx
app/components/walletSelector/WalletSelectorNavigation.spec.tsx
app/components/walletSelector/WalletSelectorNavigation.tsx
app/components/walletSelector/walletRegister/RegisterWallet.tsx
app/components/walletSelector/walletRegister/WalletLight.tsx
app/components/walletSelector/walletRegister/WalletLightLoginRouter.tsx
app/modules/routing/actions.ts
app/modules/routing/selectors.ts
app/store.ts

Login routes vol 1

---

app/lib/web3/LightWallet.ts
app/lib/web3/lightWallet.spec.node.ts
app/modules/wallet-selector/light-wizard/actions.spec.ts
app/modules/wallet-selector/light-wizard/flows.ts
yarn.lock

This pr changes the Vault Key derivation Algorithm to fit specs found on 
https://github.com/Neufund/platform-backend/wiki/1.-Platform-Architecture-Overview#wallet-storage-api

Fixes Vault Key derivation 

---

app/components/App.tsx
app/components/modals/GenericErrorModal.tsx
app/modules/actions.ts
app/modules/genericErrorModal/actions.ts
app/modules/genericErrorModal/reducer.ts
app/modules/wallet-selector/light-wizard/actions.spec.ts
app/modules/wallet-selector/light-wizard/errors.ts
app/modules/wallet-selector/light-wizard/flows.ts
app/store.ts

Also this Connects Generic Error model with Register lightwallet

Adds Generic Error model

---

app/components/AppRouter.tsx
app/components/Header.module.scss
app/components/dashboard/Dashboard.tsx
app/components/layouts/LayoutAuthorized.module.scss
app/components/layouts/LayoutAuthorized.tsx
app/components/layouts/LayoutRegisterLogin.module.scss
app/components/shared/ProgressStepper.module.scss
app/components/walletSelector/WalletBrowser.module.scss
app/components/walletSelector/WalletLedgerChooserComponent.module.scss
app/components/walletSelector/WalletLedgerChooserTableAdvanced.module.scss
app/components/walletSelector/WalletLedgerChooserTableSimple.module.scss
app/components/walletSelector/WalletSelector.module.scss
app/styles/overrides.scss
app/styles/utils.scss
app/styles/variables.scss

Colors were just added temporarily for presentation purpose. Routing will be improved in separate PR (common layout for all authorized views).
Closes #281

Layout for authorized views

---

app/components/Demo.tsx
app/components/dashboard/Dashboard.tsx
app/components/dashboard/UserInfo.tsx
app/components/dashboard/myPortfolio/MyPortoflioWidger.tsx
app/components/shared/PanelDark.module.scss
app/components/shared/PanelDark.tsx

make PanelDark header height fixed, dashboard layout basics

---

app/components/Demo.tsx
app/components/shared/Menu.utils.spec.ts
app/components/shared/Money.spec.tsx
app/components/shared/Money.tsx
app/components/shared/Money.utils.ts
app/config/constants.ts
app/modules/money/reducer.ts
app/store.ts

Money component

---

app/components/Demo.tsx
app/components/shared/BreadCrumb.spec.tsx
app/components/shared/BreadCrumb.tsx

Add BreadCrumb component

---

app/styles/overrides.scss
app/styles/typography.scss
webpack/webpack.config.prod.js

- fix svg inlining in produciton builds
- fix placement of antyaliasing css rule

Small fixes

---

app/components/settings/backupSeed/BackupSeedDisplay.tsx

removes goToNextStep Button from viewSeed modal

---

app/components/Demo.tsx
app/components/dashboard/myWallet/MyWalletWidget.tsx
app/components/shared/MoneySuiteWidget.tsx
app/lib/web3/ContractsService.ts
app/lib/web3/Web3Manager.ts
app/modules/accessWallet/sagas.ts
app/modules/wallet-selector/browser-wizard/flows.ts
app/modules/wallet-selector/ledger-wizard/flows.ts
app/modules/wallet/sagas.ts

Blockchain wallet data

---

app/modules/auth/reducer.ts
app/modules/auth/sagas.ts
app/store.ts

clears whole state during logout

---

app/components/dashboard/notification-widget/NotificationWidget.tsx
app/modules/auth/sagas.ts
app/modules/notifications/reducer.ts

fixes backCodeVerified when wallet is not neuWallet

---

app/components/dashboard/myWallet/MyWalletWidget.module.scss
app/components/shared/PanelDark.module.scss
app/components/shared/PanelDark.tsx

Previously it was broken on smaller breakpoints.

Fix DarkPanel header height

---

app/components/settings/verifyEmail/VerifyEmailWidget.tsx
app/modules/auth/selectors.ts

adds email to verifyEmail Widget

---

app/modules/wallet/selectors.spec.ts
app/modules/wallet/selectors.ts
app/utils/BigNumberUtils.spec.ts
app/utils/BigNumberUtils.ts

Fix wallet calcs

---

app/components/layouts/LayoutAuthorizedMenu.module.scss
app/components/layouts/LayoutAuthorizedMenu.spec.tsx
app/components/layouts/LayoutAuthorizedMenu.tsx

adds ETO menu to layout

---

app/components/Demo.tsx
app/components/wallet/wallet-balance/WalletBalance.module.scss
app/components/wallet/wallet-balance/WalletBalance.tsx

Improve WalletBalance component

---

app/components/shared/forms/formField/FormField.module.scss
app/components/shared/forms/formField/FormField.tsx
app/components/shared/forms/formField/FormTextArea.tsx
app/components/walletSelector/light/RegisterLightWallet.tsx
package.json
yarn.lock

fixes FormField error message

---

app/components/shared/forms/formField/FormError.module.scss
app/components/shared/forms/formField/FormField.tsx
app/components/shared/forms/formField/FormFieldDate.module.scss
app/components/shared/forms/formField/FormFieldDate.tsx
app/components/shared/forms/formField/FormSelectField.tsx
app/lib/api/util/schemaHelpers.ts

Add error label to select field

---

app/di/setupBindings.ts
app/index.tsx
app/lib/dependencies/Logger.ts
app/lib/persistence/ObjectStorage.spec.ts
app/lib/web3/Web3Manager.spec.ts
app/modules/auth/sagas.spec.ts
app/modules/init/__tests__/reducer.spec.ts
app/modules/init/sagas.ts
app/modules/wallet-selector/browser-wizard/actions.spec.ts
app/modules/wallet-selector/light-wizard/actions.spec.ts
app/modules/web3/sagas.spec.ts
app/utils/AsyncIntervalScheduler.spec.ts
test/fixtures.ts
test/integrationTestUtils.tsx

- remove some redux middlewares on prod

Prod fixes

---

app/components/walletSelector/WalletSelector.integration.spec.tsx
app/modules/wallet-selector/ledger-wizard/actions.spec.ts
app/modules/wallet-selector/ledger-wizard/flows.ts
test/integrationTestUtils.tsx
typings/modifications.d.ts

Fix missing NEU ammount on ledger address selector

---

app/components/walletSelector/light/LoginWithEmailLightWallet.tsx
app/modules/wallet-selector/light-wizard/reducer.ts
intl/locales/en-en.json

Lightwallet login improvements

---

.babelrc
@types/crypto-random-string/index.d.ts
@types/hex2ascii/index.d.ts
@types/promise-all/index.d.ts
app/di/setupBindings.ts
app/di/symbols.ts
app/index.tsx
app/lib/dependencies/cryptoRandomString.ts
app/lib/intl/IntlWrapper.ts
app/lib/web3/BrowserWallet.ts
app/lib/web3/ContractsService.ts
app/modules/kyc/sagas.ts
app/modules/wallet/sagas.ts
app/utils/IntlProviderAndInjector.tsx
intl/locales/en-en.json
package.json
scripts/extract-intl-messages.sh
tsconfig.dev.json
tsconfig.json
typings/promise-all.d.ts
yarn.lock

- fix babel config to find translations ids also in ts files
- put intl into inversify container
- fix typings mostly b/c babel cant parse `const dep = import "dep"` syntax that we used.

Inject intl via container

---

app/components/kyc/business/LegalRepresentative.tsx

fixes kyc interface

---

app/components/kyc/business/BeneficialOwners.tsx
intl/locales/en-en.json

@shanile please confirm if this is how you want it?

adds disclaimer to benificial owners

---

app/components/kyc/Kyc.tsx
app/components/kyc/business/LegalRepresentative.tsx
app/components/kyc/business/Start.tsx

fixes kyc progress stepper

---

.gitignore
app/components/settings/Settings.tsx
app/components/settings/ethereumAddressWidget/YourEthereumAddressWidget.module.scss
app/components/settings/ethereumAddressWidget/YourEthereumAddressWidget.stories.tsx
app/components/settings/ethereumAddressWidget/YourEthereumAddressWidget.tsx
intl/locales/en-en.json

Ethereum address display

---

app/components/settings/ethereumAddressWidget/YourEthereumAddressWidget.module.scss

[#763] Improve ETH addres widget styles

---

app/components/shared/Tooltip.module.scss

[#766] Change tooltip's expanding direction

---

app/lib/web3/ContractsService.ts

Related: https://github.com/Neufund/platform-frontend/issues/767

Optimize web3 communication by reducing get_code calls

---

app/components/shared/forms/formField/FormField.stories.tsx
app/components/shared/forms/formField/FormField.tsx
app/components/shared/forms/formField/FormFieldDate.stories.tsx
app/components/shared/forms/formField/FormFieldDate.tsx
app/components/shared/forms/formField/FormStyles.module.scss

Related: https://github.com/Neufund/platform-frontend/issues/713

auto travel on date of birth field, fix styles for addons on form fields

---

app/components/shared/forms/formField/FormSelectCountryField.tsx

Related: https://github.com/Neufund/platform-frontend/issues/840

Add Kosovo to country list

---

app/components/eto/registration/pages/EtoTerms.tsx
app/lib/api/EtoApi.interfaces.ts
intl/locales/en-en.json

#1042 Add new filed

---

app/components/eto/registration/pages/EtoMedia.tsx
app/components/shared/forms/formField/FormField.tsx
app/lib/api/EtoApi.interfaces.ts
app/modules/eto-flow/selectors.ts
intl/locales/en-en.json

related: #1041
I could not reporduce issue with range field.

#1041 Forms small fixes

---

app/components/eto/registration/pages/EtoMedia.tsx

Add missing row @ eto media form

---

app/index.html
app/index.tsx
app/utils/googleTagManager.js
typings/files.d.ts
webpack/webpack.config.dev.js

We need to add new env var: `NF_GOOGLE_TAG_ID="UA-88781119-1"`

google tag manager integration

---

app/assets/img/eth_icon.svg

#1055 Resize ETH icon

---

app/components/shared/MultiFileUpload.module.scss
app/components/shared/forms/formField/FormFieldDate.module.scss
app/components/shared/forms/formField/FormLabel.module.scss

Improve styles

---

app/components/kyc/Kyc.tsx
intl/locales/en-en.json

related https://github.com/Neufund/platform-frontend/issues/1011

changes KYC routing for issuers

---

app/components/eto/registration/pages/KeyIndividuals.tsx

fix remove button on key individuals section. Fix arrayHelpers usage

---

app/components/dashboard/notification-widget/Notification.module.scss
app/components/dashboard/notification-widget/Notification.tsx
app/components/dashboard/notification-widget/NotificationWidget.tsx
app/components/layouts/LayoutAuthorized.tsx
app/styles/config/shadows.scss
app/styles/config/spacings.scss
app/styles/global.scss

Change notification and notification widget layout

---

app/data/etoCompanies.ts

changes founders bank

---

app/components/shared/WarningAlert.tsx

Fixes warning message responsiveness

---

app/components/eto/shared/EtoPublicComponent.tsx

#1115 Hide carousels when empty person is added

---

app/components/shared/AccountAddress.module.scss
app/components/shared/AccountAddress.tsx

#1112 Make account address multiline

---

app/components/walletSelector/light/RegisterLightWallet.tsx
app/e2e-test-utils/index.ts
app/modules/wallet-selector/light-wizard/reducer.ts

Related https://github.com/Neufund/platform-frontend/issues/1026
Also Adds E2E tests that check for this feature during registration and login

disables register button when active

---

app/components/shared/PeopleSwiperWidget.tsx

Related https://github.com/Neufund/platform-frontend/issues/1103

Fixes swiper bug

---

app/components/Documents.tsx

related: https://github.com/Neufund/platform-frontend/issues/1222

This removes requested templates from documents view

---

app/components/eto/overview/EtoTimeline.tsx
app/components/eto/shared/EtoPublicComponent.tsx

Fix default view for eto timeline

---

.circleci/config.yml
app/components/eto/EtoDashboard.tsx
dangerfile.ts

This changes the Threshold of the form for testing purposes now it will need 100% of the required fields 
https://github.com/Neufund/platform-frontend/issues/1200

Changes ETO form threshold

---

.circleci/config.yml
app/components/walletSelector/walletRecover/__tests__/WalletRecover.spec.e2e.ts
e2e/setup-e2e.sh

Update for e2e tests

---

app/modules/eto-flow/actions.ts
app/modules/eto-flow/reducer.ts
app/modules/eto-flow/sagas.ts

Changes ETO Forum to stay in place when an error occurs

---

app/components/walletSelector/WalletSelector.integration.spec.tsx
app/lib/api/users/UsersApi.ts
app/lib/api/users/fixtures.ts
app/lib/api/users/interfaces.ts
app/lib/persistence/WalletMetadataObjectStorage.ts
app/lib/web3/LedgerWallet.ts
app/lib/web3/LightWallet.spec.ts
app/lib/web3/LightWallet.ts
app/lib/web3/Web3Manager.spec.ts
app/modules/auth/sagas.ts
app/modules/wallet-selector/ledger-wizard/actions.spec.ts
app/modules/wallet-selector/light-wizard/sagas.ts
app/modules/web3/__tests__/fixtures.ts
app/modules/web3/__tests__/selectors.spec.ts

in `auth` saga when wallet type is detected, it's updated in backend
tested manually both on NULL and changed wallet types
fixes #1050

updates user on wallet type change

---

app/components/dashboard/eto-list/EtoList.tsx
app/components/eto/overview/EtoOverviewStatus/EtoOverviewStatus.tsx
app/components/eto/overview/EtoOverviewStatus/TagsWidget.tsx
app/components/eto/shared/EtoPublicComponent.tsx
app/modules/eto-documents/sagas.ts

1. pre-chain etos are listed (previously were filtered out). new io build will include all possible pre-chain states
2. issuer dashboard for a new user now takes company and eto before documents. new io build will persist all objects on first get
3. other small fixes

several fixes that make testing possible

---

app/modules/public-etos/sagas.ts

bug is here: https://github.com/ethereum/web3.js/pull/896

 sends bignumber as string to raw web3 call due to web3 bug (#896)

---

app/components/eto/overview/EtoOverviewStatus/EtoOverviewStatus.tsx
app/components/eto/overview/EtoOverviewStatus/TagsWidget.tsx
app/components/eto/publicView/EtoInvestmentTermsWidget.tsx
app/components/modals/txSender/investment-flow/BankTransferSummary.tsx
app/components/modals/txSender/investment-flow/Summary.tsx
app/lib/api/ImmutableStorageApi.ts
app/modules/public-etos/actions.ts
app/modules/public-etos/sagas.ts

fixes: #1578 
also fixes
- templates were downloaded instead of documents (in several places)
- eto/pr eto countdown was not shown in setup
- isEligibleForEto slightly improved (but still needs update)
that's needed for tomorrows tests

simplifies documents download

---

app/components/shared/AccountBalance.module.scss
app/components/shared/buttons/Button.module.scss
app/components/wallet/wallet-balance/IcbmWallet.tsx
app/components/wallet/wallet-balance/LockedWallet.tsx
app/components/wallet/wallet-balance/UnlockedWallet.tsx
app/components/wallet/wallet-balance/WalletBalance.module.scss
app/components/wallet/wallet-balance/WalletBalance.tsx

#1618 [INVESTOR WALLET] Delimiter lines in wallet should be aligned

---

app/components/shared/DocumentLink.tsx

fix minor styling issues in documents in eto public view

#1746 Styling issues of Documents in Eto Public View

---

docs/component-development-guidelines.md

This reverts commit 7f9ea9b3f70e81bbc3505d0b3d0bf694bf672be2, reversing
changes made to cbbc01099db8cb9fb231b4ad92bcb557253b8531.

Revert "Merge pull request #1812 from Neufund/Moe/Guidelines"

---

app/modules/tx/transactions/sagas.ts
app/modules/tx/validator/sagas.ts

related https://github.com/Neufund/platform-frontend/issues/1853

logs false errors as info

---

app/components/eto/overview/EtoOverviewStatus/EtoOverviewStatus.module.scss
app/components/eto/overview/EtoOverviewStatus/TagsWidget.tsx
app/components/eto/shared/EtoTagWidget.tsx
app/components/eto/shared/TagsEditor.tsx
app/components/shared/Tabs.module.scss
app/components/shared/Tag.module.scss
app/components/shared/Tag.stories.tsx
app/components/shared/Tag.tsx
app/components/shared/forms/form-field/FormStyles.module.scss
app/styles/elements/a.scss
app/styles/tools/typography.scss

#1856 Eto visual fixes

---

app/components/settings/backup-seed/BackupSeed.module.scss
app/components/settings/backup-seed/BackupSeedIntro.tsx
app/components/shared/StepCard.module.scss
app/components/shared/StepCard.tsx
app/components/wallet-selector/browser/WalletBrowser.module.scss
app/components/wallet-selector/browser/WalletBrowser.tsx
intl/locales/en-en.json

remove metamask logo and one of three step imgs.
btw rebuild StepCard element to remove markup clutter

#1903 visual fixes to metamask register screen

---

app/components/settings/Settings.tsx

This reverts commit a966155f26b56627d12aa13618ec4a00338eabe6.

Revert "removes loadKycIndividual from settings (#1919)"

---

app/components/settings/verify-email/VerifyEmailWidget.tsx

Related: https://github.com/Neufund/platform-frontend/issues/1949

#1949 Removes bold From VerifyEmailWidget

---

app/components/wallet-selector/light/MissingEmailLightWallet.tsx
intl/locales/en-en.json

add link to help center to light wallet screen

#1887 add link to recovery/help center on the light wallet screen

---

webpack/webpack.config.dev.js

Turn on source maps for styles

---

app/components/modals/tx-sender/investment-flow/utils.tsx

shoudl update wallet selector text.

add eur to direct bank transfer

---

app/components/kyc/Kyc.tsx

small PR that makes the kyc screen button always lead back to profile and not to the dashboard

switch kyc button to profile

---

app/components/eto/overview/EtoOverviewStatus/CampaigningWidget/CampaigningActivatedWidget.tsx
app/modules/auth/sagas.ts
app/modules/auth/selectors.ts
app/modules/init/sagas.ts
intl/locales/en-en.json

fix terms of use

---

app/components/shared/TwitterTimeline.module.scss
app/external/twitter-iframe.html

Related: https://github.com/Neufund/platform-frontend/issues/2084

Limits twitter and fixes style

---

app/components/eto/EtoPublicView.tsx
app/components/eto/EtoPublicViewByContractId.tsx
app/components/eto/overview/EtoOverviewStatus/CampaigningWidget/CampaigningActivatedWidget.tsx
app/components/eto/overview/EtoOverviewStatus/ClaimRefundWidget/withCanClaimToken.ts
app/components/kyc/Kyc.tsx
app/components/kyc/Router.tsx
app/components/layouts/Header.tsx
app/components/layouts/LayoutAuthorizedMenu.tsx
app/components/modals/accept-tos-modal/AcceptTosModal.tsx
app/components/settings/Settings.tsx
app/components/settings/kyc-states/KycStatusWidget.tsx
app/components/shared/routing/OnlyAuthorizedRoute.tsx
app/lib/persistence/WalletStorage.ts
app/modules/auth/actions.ts
app/modules/auth/sagas.ts
app/modules/auth/selectors.ts
app/modules/init/sagas.ts
app/modules/public-etos/sagas.ts
app/test-e2e/eto/Campaining.spec.e2e.ts
app/test-e2e/register/LightWalletETOLogin.spec.e2e.ts
app/test-e2e/register/LightWalletETORegister.spec.e2e.ts
app/test-e2e/settings/LightWalletRegister.spec.e2e.ts
app/test-e2e/settings/VerifyEmailWidget.spec.e2e.ts
app/test-e2e/utils/userHelpers.ts
cypress/cypress-retries.js

should solve 
https://circleci.com/gh/Neufund/platform-frontend/21517#tests/containers/1

Adds a second catch

---

app/modules/investment-flow/__tests__/selectors.spec.ts
app/modules/investment-flow/selectors.ts

updates message for euro token bank transfer

---

app/components/modals/tx-sender/investment-flow/InvestmentTypeSelector.stories.tsx
app/components/modals/tx-sender/investment-flow/utils.tsx

Related https://github.com/Neufund/platform-frontend/issues/2127

#2127 Changes Euro Investment Naming

---

app/components/wallet-selector/light/LoginWithEmailLightWallet.tsx

Fixes https://sentry.neusrv.net/sentry/production/issues/2289/

Fix PRODUCTION-7A fatal error

---

app/components/shared/charts/ChartDoughnut.module.scss
app/components/shared/charts/ChartDoughnut.stories.tsx
app/components/shared/charts/ChartDoughnut.tsx

add custom tooltip function, tooltip styles, typings

#2101 Fix tooltips in doughnut chart

---

app/components/eto/shared/EtoPublicComponent.tsx
app/components/shared/MediaLinksEditor.tsx

Related: https://github.com/Neufund/platform-frontend/issues/2155

#2155 Removes reverse from media links

---

app/components/AppRouter.tsx
app/components/appRoutes.ts
app/components/edge-cases/MigrationFromLink.tsx
app/components/settings/icbm-wallet-widget/CheckYourICBMWalletWidget.tsx
app/test-e2e/wallets/WalletMigrate.spec.e2e.ts

Related: https://github.com/Neufund/platform-frontend/issues/1963

Adds special route for migration tool

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/new_feature.md

adds new feature template

---

package.json
yarn.lock

This will reduce the time Webpack takes to build the bundle

updates webpack

---

.circleci/config.yml

This will temprorary remove chrome tests

temporary removes chrome tests

---

app/components/modals/walletAccess/AccessWalletModal.tsx
app/modules/generic-modal/sagas.ts
app/modules/kyc/sagas.ts
app/modules/wallet-selector/light-wizard/sagas.ts
app/test-e2e/utils/userHelpers.ts
e2e/run_backend.sh

fixes translation bugs in displayInfoModalSaga
changes neuCall to simple saga::call since we don't need dep.injection in this saga any more

[hotfix] At/#2380 fix translations in displayInfoModalSaga

---

app/index.tsx

This PR disables service workers.

Disable SW

---

.github/ISSUE_TEMPLATE/bug-report.md

Updating fields in the bug report template. would be then applicable to zenhub

update bug report template

---

app/components/modals/accept-tos-modal/AcceptTosModal.tsx

Cherry-pick on production branch of #2427

[hotfix] Fix TOS on mobile devices

---

package.json
yarn.lock

Some refactoring was done in the lightwallet project
https://github.com/Neufund/eth-lightwallet/pull/15
Tested: 
With browser stack IPHONE xs

2425 - Solves IOS lightwallet login issue

---

app/components/dashboard/Dashboard.stories.tsx
app/components/eto/EtoDashboard.stories.tsx
app/components/eto/EtoDashboard.tsx
app/components/settings/Settings.stories.tsx
app/components/settings/Settings.tsx
app/components/settings/backup-seed/BackupSeedWidget.tsx
app/components/settings/kyc-states/KycStatusWidget.tsx
app/components/settings/settings-widget/SettingsWidgets.tsx
test/fixtures/mockedStore.ts

2442 - fix visual glitch

---

app/utils/myEtherWallet.ts
e2e/run_backend.sh

2450 - changes myetherwallet link

---

app/components/wallet-selector/wallet-recover/help/LoginHelp.tsx
app/components/wallet-selector/wallet-recover/recovery/RecoverWallet.tsx
intl/locales/en-en.json

change the link to support on Restore Light Wallet screen
add Back button to Restore Light Wallet screen

#2026 change external link in wallet recovery

---

app/components/modals/tx-sender/redeem/BankTransferRedeemInit.module.scss
app/components/modals/tx-sender/redeem/BankTransferRedeemInit.tsx
app/components/modals/tx-sender/redeem/CalculatedFee.tsx
app/components/modals/tx-sender/redeem/TotalRedeemed.tsx
app/components/shared/forms/fields/FormFieldRaw.tsx
app/components/shared/forms/fields/FormInput.tsx
app/components/shared/forms/fields/FormInputRaw.tsx
app/components/shared/forms/fields/FormMaskedInput.stories.tsx
app/components/shared/forms/fields/FormMaskedInput.tsx
app/components/shared/forms/fields/utils.tsx
app/components/shared/forms/index.tsx
app/components/wallet/wallet-balance/UnlockedNEURWallet.tsx
app/test-e2e/bank-transfer/Purchase.spec.e2e.ts
app/test-e2e/bank-transfer/RedeemNEUR.spec.e2e.ts
app/test-e2e/bank-transfer/assertions.ts

#2534 #2559 #1484 Add MaskedInput to NEUR Redeem

---

.storybook/config.js
app/components/App.tsx
app/components/eto/registration/pages/EtoTerms.tsx
app/components/settings/icbm-wallet-widget/CheckYourICBMWalletWidget.tsx
app/components/shared/forms/Form.ts
app/components/shared/tooltips/Tooltip.tsx
app/components/utils/omitProps.ts
app/test-e2e/eto-registration/EtoTerms.spec.e2e.ts
e2e/run_backend.sh

It's safe to merge the whole master as there is only one logic change #2766

Production hotfix related to Warp release

---

app/utils/OnEnterAction.tsx
app/utils/onEnterAction.spec.tsx

move class declaration out of onEnterAction() function

#3016 fix memory leak in onEnterAction()

---

app/components/shared/SlidePerson.tsx

this pr disables showing texts in team/advisers etc slider

[hotfix] disable texts in slider

---

app/components/eto/shared/routing/withJurisdictionRoute.ts

HOTFIX - Case Insensitivity Check Production

---

app/test-e2e/bank-transfer/assertions.ts
app/test-e2e/settings/LightWalletRegister.spec.e2e.io.ts
app/test-e2e/utils/assertions.ts
app/test-e2e/utils/index.ts

This PR adds the updates for the changed sendgrid_mock. To be merged after this change has made it onto the backend master

[don't merge] updates email parsing for sendgrid_mock

---

packages/web/app/components/eto/public-view/DocumentsWidget.tsx
packages/web/app/components/eto/shared/ETOState.tsx
packages/web/app/lib/api/eto/EtoFileUtils.ts
packages/web/health-check-sha.json

* Changes colors
* Hides Documents
* Updates Artifacts

[PROD HOTFIX - MASTER MERGE] Remove Documents + Change Colors (#3460)

---

packages/web/app/components/issuer-dashboard/chooseEtoStartDateWidget/ChooseEtoStartDateWidget.tsx

Unblock set start date (#3467)

Blue_Tunes Production RC 4

---

packages/web/app/modules/nominee-flow/utils.ts
packages/web/health-check-sha.json

(cherry picked from commit d4a4655a387d15f37ced5dafd51cf8e0a8cb5e35)

[Hotfix] Make link bank account optional

---

packages/web/app/components/layouts/menus/MenuEntry.module.scss
packages/web/app/components/settings/verify-email/VerifyEmailWidget.module.scss

**Technical notes**
Fixes two bugs @glupiawymowka found while testing buttons

Small fixes to buttons

---

.circleci/config.yml
packages/web/health-check-sha.json
packages/web/package.json

Let's see if it helps with visual regression stability

Reduce visual regression parallel runs to 8

---

packages/web/app/components/eto/eto-full-view/shared/campaign-overview/individuals/Individuals.tsx
packages/web/app/components/eto/eto-full-view/shared/campaign-overview/individuals/utils.ts
packages/web/app/components/shared/PeopleSwiperWidget.tsx

* update go left, go right
* fix selectedTabIndex
* use close to 0 & cleanup
* Fix one tab case
* format

Sol Music Production RC Pt3

---

packages/web/app/components/eto/eto-full-view/shared/EtoAccordionElements.tsx
packages/web/app/components/eto/eto-full-view/shared/campaign-overview/fundrising-stats/EtoViewFundraisingStatistics.tsx
packages/web/app/components/eto/eto-full-view/shared/campaign-overview/legal-information-widget/LegalInformationWidget.module.scss
packages/web/app/components/eto/eto-full-view/shared/campaign-overview/legal-information-widget/LegalInformationWidget.tsx
packages/web/app/components/eto/registration/pages/EtoPitch/EtoRegistrationPitch.tsx
packages/web/app/components/eto/registration/pages/EtoPitch/validateEtoRegistrationPitch.tsx
packages/web/app/components/shared/MediaLinksEditor.tsx
packages/web/app/components/shared/MediaLinksWidget.tsx
packages/web/app/components/shared/charts/ChartLegend.module.scss
packages/web/app/config/.env.common
packages/web/app/config/externalRoutes.ts
packages/web/app/config/getConfig.ts
packages/web/app/lib/api/eto/EtoApi.interfaces.unsafe.ts
packages/web/app/test-e2e/issuer/eto/fixtures.ts
packages/web/app/test-e2e/issuer/eto/view/components/MediaLinksWidget.spec.e2e.io.ts
packages/web/health-check-sha.json
packages/web/intl/locales/en-en.json
packages/web/test/fixtures.ts

#4166 Fix legal information widget word-break (#4174)

Dharma Production RC pt 2

---

packages/web/app/external/unsupported-browser/check-browser-support.js
packages/web/app/index.html

Move browser support check to external script (#4261)

Timecode Production RC pt 3

---

packages/web/app/modules/eto-view/notAuth/sagas.ts

Fix exception for watchSetEtoViewAction 

---

packages/web/app/components/modals/tx-sender/investment-flow/Investment.tsx
packages/web/app/modules/investment-flow/sagas.ts

add guards to avoid 0 eth as investment input

Fix invest all with empty eth wallet

---

packages/design-system/.storybook/main.js
packages/design-system/package.json
packages/design-system/src/components/inputs/Checkbox.module.scss
packages/design-system/src/components/inputs/Checkbox.stories.tsx
packages/design-system/src/components/inputs/Checkbox.tsx
packages/design-system/src/components/inputs/VirtualizedSelect.module.scss
packages/web/app/components/modals/tx-sender/investor-payout/AcceptSummary.module.scss
packages/web/app/components/modals/tx-sender/investor-payout/AcceptSummary.tsx
packages/web/app/components/shared/WarningAlert.module.scss
yarn.lock

**Testing notes**
Checkbox was broken in #4540 so let's make sure that payout lower than gas checkbox is still working properly.
Also this PR makes checkboxes in sync with design-system https://app.zeplin.io/project/5dcae4b293ec9fff68a73bdd/screen/5e4e8ea8a469bb7a97b85620 and adds missing states (hover on label and focus)

#4554 Fix broken inputs
